-- Generated by supabase/build-lockdown.mjs — do not hand-edit, re-run the generator.
--
-- Every SECURITY DEFINER function here was created without an explicit GRANT, so Postgres
-- applied its default: EXECUTE to PUBLIC. A definer function runs as its owner and so
-- ignores the RLS protecting the tables underneath, which turned each of these into a way
-- past those policies. All of the following were confirmed working for a logged-out
-- visitor holding only the project's public anon key — a key that ships inside the web
-- bundle by design, so "anonymous" here means anyone who has ever opened the site:
--
--   get_customers_with_stats   every customer's name, email, phone, order count and
--                              lifetime spend, pageable with p_limit / p_offset
--   get_customer_stats         the same figures for any single customer id
--   deduct_inventory_fifo      decremented real stock (98 -> 97 on a live product)
--   notify_user                wrote an arbitrary notification into a real admin account
--   is_admin_email             confirmed which email addresses are administrators
--
-- The two order-path functions took a customer id on trust, so a caller could name
-- somebody else and have the ownership check further down validate the wrong pair.
--
-- Guards are added alongside the grants, not instead of them: a GRANT revoked today can
-- be re-granted tomorrow by a migration that assumed a default it did not check, and a
-- function with no in-body authorisation is then wide open again.


-- ==========================================================================
-- get_customers_with_stats — admin only
-- ==========================================================================
create or replace function public.get_customers_with_stats(p_query text DEFAULT NULL::text, p_limit integer DEFAULT 20, p_offset integer DEFAULT 0)
returns TABLE(id uuid, name text, email text, phone text, role text, avatar_url text, created_at timestamp with time zone, order_count bigint, total_spent numeric)
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Anon-callable and unguarded: any logged-out visitor could page the whole customer
  -- list out of this, because SECURITY DEFINER ignores the RLS on profiles and orders.
  if not public.is_admin() then
    raise exception 'Only admins can query customers';
  end if;
  return query

  select
    p.id,
    p.name,
    p.email,
    p.phone,
    p.role,
    p.avatar_url,
    p.created_at,
    coalesce(o.order_count, 0) as order_count,
    coalesce(o.total_spent, 0) as total_spent
  from public.profiles p
  left join (
    select customer_id, count(*)::bigint as order_count, sum(total)::numeric as total_spent
    from public.orders
    group by customer_id
  ) o on o.customer_id = p.id
  where p.role = 'customer'
    and (
      p_query is null or p_query = ''
      or p.name ilike '%' || p_query || '%'
      or coalesce(p.email,'') ilike '%' || p_query || '%'
      or coalesce(p.phone,'') ilike '%' || p_query || '%'
    )
  order by p.created_at desc
  limit p_limit offset p_offset;
end;
$$;


-- ==========================================================================
-- get_customer_stats — admin only
-- ==========================================================================
create or replace function public.get_customer_stats(p_customer_id uuid)
returns TABLE(order_count bigint, total_spent numeric)
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Anon-callable and unguarded: any logged-out visitor could page the whole customer
  -- list out of this, because SECURITY DEFINER ignores the RLS on profiles and orders.
  if not public.is_admin() then
    raise exception 'Only admins can query customers';
  end if;
  return query

  select count(*)::bigint as order_count, coalesce(sum(total),0)::numeric as total_spent
  from public.orders where customer_id = p_customer_id;
end;
$$;


-- ==========================================================================
-- create_order — caller must be the customer they name
-- ==========================================================================
create or replace function public.create_order(p_customer_id uuid, p_address_id uuid)
returns uuid
language plpgsql
security definer
set search_path = public
as $$

declare
  v_order_id uuid;
  v_existing_id uuid;
  v_existing_subtotal numeric;
  v_existing_discount numeric;
  v_subtotal numeric := 0;
  v_cart_subtotal numeric := 0;
  v_discount numeric := 0;
  v_delivery_fee numeric;
  v_total numeric := 0;
  v_customer_name text;
  v_address_text text;
  v_address_district text;
  v_cart_item record;
  v_product record;
  v_inv record;
  v_remaining integer;
  v_total_stock integer;
begin
  -- This took p_customer_id on trust, so a caller could name a different customer and
  -- have the ownership check further down validate that wrong pair. The app only ever
  -- passes the signed-in user's own id, so requiring that costs nothing and closes
  -- the impersonation.
  if auth.uid() is distinct from p_customer_id then
    raise exception 'Customer ID must match authenticated user';
  end if;
  select name into v_customer_name from public.profiles where id = p_customer_id;
  if not found then
    raise exception 'Customer not found';
  end if;
  if not exists (select 1 from public.cart_items where user_id = p_customer_id) then
    raise exception 'Cart is empty';
  end if;

  -- Refuse a missing address outright rather than defaulting it to an empty string.
  if p_address_id is null then
    raise exception 'Delivery address is required';
  end if;

  -- Ownership is part of the lookup, not a separate check afterwards. SECURITY DEFINER
  -- bypasses RLS on `addresses`, so the `user_id = p_customer_id` predicate here is the
  -- ONLY thing standing between a caller and another customer's address.
  --
  -- An address that does not exist and one that belongs to somebody else are deliberately
  -- reported the same way, so this cannot be used to confirm whether an id is real.
  select street || ', ' || city || coalesce(', ' || county, '') || coalesce(', ' || postal_code, ''),
         county
    into v_address_text, v_address_district
  from public.addresses
  where id = p_address_id and user_id = p_customer_id;

  if v_address_text is null then
    raise exception 'Delivery address not found';
  end if;

  -- NOT NULL on street/city does not stop an empty string, and the client-side check is
  -- bypassable, so an unusable address is refused here rather than at delivery time.
  if btrim(v_address_text) in ('', ',') then
    raise exception 'Delivery address is incomplete';
  end if;

  -- Priced from the district, not hard-coded. A null or unrecognised district falls to the
  -- standard rate inside delivery_fee_for_district() rather than needing a guard here.
  v_delivery_fee := public.delivery_fee_for_district(v_address_district);

  -- Check for existing PENDING invoice for this customer (row-level lock to prevent race)
  --
  -- `delivery_fee` is deliberately no longer selected out. It used to be read into
  -- `v_existing_delivery_fee` and carried into the recalculated total, which kept the old
  -- charge on an order whose address had changed. The fee is now recomputed from the
  -- address passed to this call, so there is nothing here for the existing row to
  -- contribute.
  select id, subtotal, discount into v_existing_id, v_existing_subtotal, v_existing_discount
  from public.orders
  where customer_id = p_customer_id and status = 'PENDING'
  order by created_at desc
  limit 1
  for update;

  -- Validate cart items and compute cart subtotal (products must exist and be active)
  for v_cart_item in select * from public.cart_items where user_id = p_customer_id loop
    select * into v_product from public.products where id = v_cart_item.product_id and is_active = true;
    if not found then
      raise exception 'Product not available';
    end if;
    -- Authoritative available stock = non-expired inventory sum, falling back to
    -- products.stock only for legacy products with no inventory rows at all.
    select coalesce(sum(quantity), 0) into v_total_stock
    from public.inventory_items
    where product_id = v_cart_item.product_id
      and (expiry_date is null or expiry_date >= current_date);
    if v_total_stock = 0 and not exists (select 1 from public.inventory_items where product_id = v_cart_item.product_id) then
      v_total_stock := v_product.stock;
    end if;
    if v_total_stock < v_cart_item.quantity then
      raise exception 'Insufficient stock for product %', v_product.name;
    end if;
    v_cart_subtotal := v_cart_subtotal + (v_product.price * v_cart_item.quantity);
  end loop;

  if v_existing_id is not null then
    -- Append to existing PENDING invoice
    v_order_id := v_existing_id;
    for v_cart_item in select * from public.cart_items where user_id = p_customer_id loop
      select * into v_product from public.products where id = v_cart_item.product_id;
      -- Handle duplicate product in same order: merge quantity if already exists
      if exists (select 1 from public.order_items where order_id = v_order_id and product_id = v_cart_item.product_id) then
        update public.order_items
        set quantity = quantity + v_cart_item.quantity,
            total = (quantity + v_cart_item.quantity) * v_product.price
        where order_id = v_order_id and product_id = v_cart_item.product_id;
      else
        insert into public.order_items (order_id, product_id, product_name, quantity, unit_price, discount_percent, total)
        values (v_order_id, v_cart_item.product_id, v_product.name, v_cart_item.quantity, v_product.price, 0, v_product.price * v_cart_item.quantity);
      end if;
      perform public.deduct_inventory_fifo(v_cart_item.product_id, v_cart_item.quantity);
    end loop;
    -- Recalc totals: subtotal + cart, one delivery fee.
    --
    -- The fee is REPRICED from the address passed in here, rather than carried over from
    -- the existing order. This line used to read
    -- `coalesce(v_existing_delivery_fee, v_delivery_fee)`, which was harmless while the fee
    -- was a constant and is wrong now: a customer who first ordered to Chattogram and then
    -- added an item while switching to a Dhaka address would keep paying the 150 they were
    -- quoted, against an 80 rate. `delivery_fee` is written explicitly below too, so the
    -- stored row and the new total cannot disagree with each other either.
    v_subtotal := coalesce(v_existing_subtotal, 0) + v_cart_subtotal;
    v_total := v_subtotal - coalesce(v_existing_discount, 0) + v_delivery_fee;
    update public.orders
    set subtotal = v_subtotal,
        delivery_fee = v_delivery_fee,
        total = v_total,
        updated_at = now(),
        -- Always the address just validated. This used to be
        -- `case when v_address_text <> '' then v_address_text else address end`, which kept
        -- whatever was there before; with the guard above v_address_text is never empty,
        -- so the fallback is dead code that would only ever preserve a stale address.
        address = v_address_text,
        timeline = coalesce(timeline, '[]'::jsonb) || jsonb_build_array(jsonb_build_object('label', 'ITEMS_ADDED', 'time', now()::text, 'note', v_cart_subtotal::text || ' added'))
    where id = v_order_id;
  else
    -- No pending invoice: create new as before
    v_subtotal := v_cart_subtotal;
    v_total := v_subtotal - v_discount + v_delivery_fee;
    insert into public.orders (order_number, customer_id, customer_name, status, subtotal, discount, delivery_fee, total, payment_method, address)
    values (null, p_customer_id, v_customer_name, 'PENDING', v_subtotal, v_discount, v_delivery_fee, v_total, 'CASH_ON_DELIVERY', v_address_text)
    returning id into v_order_id;
    for v_cart_item in select * from public.cart_items where user_id = p_customer_id loop
      select * into v_product from public.products where id = v_cart_item.product_id;
      insert into public.order_items (order_id, product_id, product_name, quantity, unit_price, discount_percent, total)
      values (v_order_id, v_cart_item.product_id, v_product.name, v_cart_item.quantity, v_product.price, 0, v_product.price * v_cart_item.quantity);
      perform public.deduct_inventory_fifo(v_cart_item.product_id, v_cart_item.quantity);
    end loop;
  end if;

  delete from public.cart_items where user_id = p_customer_id;
  return v_order_id;
end;

$$;


-- ==========================================================================
-- validate_return — caller must be the customer they name
-- ==========================================================================
create or replace function public.validate_return(p_order_id uuid, p_customer_id uuid)
returns boolean
language plpgsql
security definer
set search_path = public
as $$

declare
  v_order_status text;
begin
  -- This took p_customer_id on trust, so a caller could name a different customer and
  -- have the ownership check further down validate that wrong pair. The app only ever
  -- passes the signed-in user's own id, so requiring that costs nothing and closes
  -- the impersonation.
  if auth.uid() is distinct from p_customer_id then
    raise exception 'Customer ID must match authenticated user';
  end if;
  select status into v_order_status from public.orders where id = p_order_id;
  if not found then
    raise exception 'Order not found';
  end if;
  if v_order_status != 'DELIVERED' then
    raise exception 'Returns are only allowed for delivered orders';
  end if;
  if not exists (select 1 from public.orders where id = p_order_id and customer_id = p_customer_id) then
    raise exception 'Order does not belong to customer';
  end if;
  return true;
end;

$$;


-- ==========================================================================
-- Grants. Postgres handed EXECUTE to PUBLIC on each of these at creation time; the
-- default is why none of them was ever reviewed.
-- ==========================================================================
revoke all on function public.deduct_inventory_fifo(p_product_id uuid, p_quantity integer) from public, anon, authenticated;
revoke all on function public.notify_user(p_user_id uuid, p_title text, p_body text, p_type text) from public, anon, authenticated;
revoke all on function public.is_admin_email(p_email text) from public, anon, authenticated;
revoke all on function public.rls_auto_enable() from public, anon, authenticated;

-- The two customer RPCs stay callable by a signed-in admin — that is who uses them — but
-- the anon/public grant they inherited goes away. The in-body is_admin() is the real
-- check; this only removes the path that had no check at all.
revoke all on function public.get_customers_with_stats(text, integer, integer) from public, anon;
revoke all on function public.get_customer_stats(uuid) from public, anon;
